
GET http://localhost:8080/ HTTP/2.0
###

GET  http://localhost:8080/Customer/9940a03b-ece7-493f-a88b-17ca3bb39a01 HTTP/2.0
Content-Type: application/json
###

PUT http://localhost:8080/Customer/Create HTTP/2.0
Content-Type: application/json

{
    "UID": "9940a03b-ece7-493f-a88b-17ca3bb39a06", 
    "Name": "John Doe", 
    "Age": 30, 
    "Email": "johndoe@example.com"
}
###