
GET http://localhost:8080/ HTTP/2.0
###

GET  http://localhost:8080/Customer/716d14fb-847c-4ac4-873b-f353880dc36b HTTP/2.0
Content-Type: application/json
###

PUT http://localhost:8080/Customer/Create HTTP/2.0
Content-Type: application/json

{
    "UID": "", 
    "Name": "John Doe", 
    "Age": 30, 
    "Email": "johndoe@example.com"
}
###

PATCH  http://localhost:8080/Customer/Update HTTP/2.0
Content-Type: application/json

{
    "UID": "716d14fb-847c-4ac4-873b-f353880dc36b", 
    "Name": "Marry", 
    "Age": 66, 
    "Email": "Marrydoe@example.com"
}
###