
GET http://localhost:8080/ HTTP/2.0
###

GET  http://localhost:8080/Customer/5892c711-8aea-495e-898f-8e959dc58b64 HTTP/2.0
Content-Type: application/json
###

PUT http://localhost:8080/Customer/Create HTTP/2.0
Content-Type: application/json

{
    "UID": "", 
    "Name": "John Doe", 
    "Age": 30, 
    "Email": "johndoe@example.com"
}
###